Show Package name when displaying PackageCard
espanso/hub-frontend pull request #38
Opened 2024-02-20 05:36 UTC by DylanLacey

Display each package's `.name` property on `PackageCard`, in small, `[]` wrapped text, just after the title. This helps users determine which packages they've already installed or used.

Resolves #35.

2024-02-21 07:36 UTC, DylanLacey commented
Great suggestion @arabello!  I've made those changes.

<img width="953" alt="Screenshot 2024-02-21 at 5 29 55 pm" src="https://github.com/espanso/hub-frontend/assets/615278/b4da1495-3b15-4386-8f27-0c3f74b66d46">

I also think it's worth making the package name more obvious on the package details screen. Yes, it's present in the install command, but I think it also belongs with the other package metadata. I added it between the package title and author because the lower amount of horizontal space made placing it inline with the title look... weird. I've included those changes; See below.

<img width="477" alt="Screenshot 2024-02-21 at 5 31 26 pm" src="https://github.com/espanso/hub-frontend/assets/615278/73cc0bc3-c479-48b6-ad3c-62c83d41dc42">

2024-02-22 16:46 UTC, arabello requested changes
It looks nice! 

Just one thing: the `package.name` was already shown as header title. If we want the `package.name` to be shown underneath the title using `PackageNamer`, we should change the [header title](https://github.com/espanso/hub-frontend/pull/38/files#diff-9a1342034ec0fd93addfcdd862fde197f5488dd882086afc36e2030cf5fd6d1fR267) to render the `package.title`. Otherwise we get a data duplication

2024-02-23 02:27 UTC, DylanLacey commented
GAH. Great point; I got mixed up because all the packages I was testing with had the same title as they did name >.>.

I've pushed those changes.

2024-02-23 17:38 UTC, arabello approved these changes

2024-04-05 01:23 UTC, AucaCoyan commented
Hello! Is this PR good to be merged? Thanks!
(BTW, I don't have write permissions, it needs a helping hand from @arabello 🙏🏼)

2024-04-07 22:23 UTC, arabello commented
Hey guys, sorry I'm used to the "who creates, merge" policy. I'm merging. @AucaCoyan I'm giving you writing permission

2024-04-07 22:24 UTC, merged

2024-04-07 23:22 UTC, AucaCoyan commented
Thank you Matteo! and congratz to @DylanLacey for the merge! 🎉